### ISSUE TITLE
compilation error word2vec.c

### ISSUE THREAD

**Issue by ziqizhang** [happycube/word2vec#1]
Hi, compiling word2vec.c produces the following error, please suggest how to fix this. Many thanks!

/tmp/264584.1.long.q/ccKLI0tH.o: In function `DoMAC1_Aligned':
word2vec.c:(.text+0x116d): undefined reference to`__builtin_assume_aligned'
word2vec.c:(.text+0x117f): undefined reference to `__builtin_assume_aligned'
/tmp/264584.1.long.q/ccKLI0tH.o: In function`DoMAC_Aligned':
word2vec.c:(.text+0x1644): undefined reference to `__builtin_assume_aligned'
word2vec.c:(.text+0x1656): undefined reference to`__builtin_assume_aligned'
/tmp/264584.1.long.q/ccKLI0tH.o: In function `TrainModelThread':
word2vec.c:(.text+0x9548): undefined reference to`__builtin_assume_aligned'
/tmp/264584.1.long.q/ccKLI0tH.o:word2vec.c:(.text+0x955a): more undefined references to `__builtin_assume_aligned' follow
collect2: ld returned 1 exit status

**Comment by happycube** [comment]
What compiler version and settings are you using (and you are using 64-bit right?)  I believe assume_aligned is in both current gcc and clang.

You can just remove the assume_aligned lines, but it will probably affect vectorization.

**Comment by ziqizhang** [comment]
thanks indeed it is the gcc compiler version problem

I re-tried with gcc 4.8.2 and now it works.

**Comment by happycube** [comment]
Should probably detect this, but I'm not too worried since the changes aren't (yet?) big enough to go upstream anyhow.
